[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = { version = "0.3.69", features = ["HtmlTextAreaElement"] }
yew = { version = "0.21.0", features = ["csr"] }
yew-hooks = "0.3.2"
